# Generated by Django 4.0.5 on 2022-07-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttle1', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
