# Generated by Django 4.0.5 on 2022-07-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('throttle1', '0003_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='throttle1.custom')),
            ],
        ),
    ]
