# Generated by Django 4.0.5 on 2022-07-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('throttle1', '0004_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownby', to='throttle1.custom'),
        ),
    ]
